/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Exact Theme Colors
        "tertiary-container": "#271901",
        "tertiary-fixed": "#fcdeb5",
        "on-secondary": "#ffffff",
        "surface-tint": "#565e74",
        "inverse-surface": "#2b3137",
        "surface-bright": "#f6f9ff",
        "on-tertiary-fixed-variant": "#574425",
        "error-container": "#ffdad6",
        "inverse-primary": "#bec6e0",
        "secondary-container": "#d0e1fb",
        "surface": "#f6f9ff",
        "secondary": "#505f76",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#98805d",
        "inverse-on-surface": "#ebf1f9",
        "outline-variant": "#c6c6cd",
        "on-primary-fixed": "#131b2e",
        "on-secondary-container": "#54647a",
        "surface-container-low": "#eef4fc",
        "outline": "#76777d",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed-dim": "#bec6e0",
        "on-background": "#161c22",
        "on-error": "#ffffff",
        "on-surface": "#161c22",
        "on-tertiary-fixed": "#271901",
        "secondary-fixed-dim": "#b7c8e1",
        "primary": "#000000",
        "surface-dim": "#d4dbe2",
        "surface-container-high": "#e3e9f1",
        "surface-container": "#e8eef6",
        "on-error-container": "#93000a",
        "surface-variant": "#dde3eb",
        "on-primary-container": "#7c839b",
        "error": "#ba1a1a",
        "surface-container-highest": "#dde3eb",
        "primary-fixed": "#dae2fd",
        "background": "#f6f9ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#dec29a",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        // Semantic market colors
        market: {
          gain: '#15803d',
          loss: '#ba1a1a',
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        none: "0px",
        sm: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        brand: ["Outfit", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "Menlo", "Consolas", "monospace"],
      },
      boxShadow: {
        subtle: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        card: '0 1px 3px 0 rgba(0, 0, 0, 0.08)',
        hover: '0 4px 12px 0 rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
